apiVersion: apps/v1
kind: Deployment
metadata:
  name: qq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qq
  template:
    metadata:
      labels:
        app: qq
    spec:
      containers:
        - name: qq
          image: sindonghyun/qq:2.0.6
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            failureThreshold: 1
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 12
          startupProbe:
            httpGet:
              path: /
              port: 8080
            failureThreshold: 10
            periodSeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
